;/*FB_PKG_DELIM*/

__d("HeroInteractionContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=function(){};c={consumeBootload:b,hold:function(){return""},logHeroRender:b,logMetadata:b,logPageletVC:b,logReactCommit:b,logReactPostCommit:b,logReactRender:b,pageletStack:[],registerPlaceholder:b,removePlaceholder:b,suspenseCallback:b,unhold:b};e=a.createContext(c);g.DEFAULT_CONTEXT_VALUE=c;g.Context=e}),98);
__d("HeroInteractionIDContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(null);g["default"]=b}),98);
__d("HeroComponent.react",["HeroInteractionContext","HeroInteractionIDContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||(h=d("react"));e=h;var i=e.useContext,j=e.useLayoutEffect;function a(a){var b=d("react-compiler-runtime").c(5),e=a.description,f=i(d("HeroInteractionContext").Context),g=i(c("HeroInteractionIDContext")),h;b[0]!==e||b[1]!==f||b[2]!==g?(a=function(){g!=null&&f.logHeroRender(g,e,f.pageletStack)},h=[e,f,g],b[0]=e,b[1]=f,b[2]=g,b[3]=a,b[4]=h):(a=b[3],h=b[4]);j(a,h);return null}a.displayName="HeroComponent";f=b.memo(a);g["default"]=f}),98);
__d("HeroCurrentInteractionForLoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({current:null});g["default"]=b}),98);
__d("HeroHoldTrigger.react",["HeroInteractionContext","HeroInteractionIDContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useContext,j=b.useLayoutEffect;function a(a){var b=d("react-compiler-runtime").c(6),e=a.description,f=a.hold,g=i(d("HeroInteractionContext").Context),h=i(c("HeroInteractionIDContext")),k;b[0]!==e||b[1]!==g||b[2]!==f||b[3]!==h?(a=function(){if(f&&h!=null){var a=g.hold(h,g.pageletStack,e);return function(){g.unhold(h,a)}}},k=[e,g,h,f],b[0]=e,b[1]=g,b[2]=f,b[3]=h,b[4]=a,b[5]=k):(a=b[4],k=b[5]);j(a,k);return null}a.displayName="HeroHoldTrigger";g["default"]=a}),98);
__d("react-relay/relay-hooks/ProfilerContext",["react"],(function(a,b,c,d,e,f){"use strict";var g;a=g||b("react");c=a.createContext({wrapPrepareQueryResource:function(a){return a()}});e.exports=c}),null);
__d("RelayProfilerContext",["react-relay/relay-hooks/ProfilerContext"],(function(a,b,c,d,e,f,g){g["default"]=c("react-relay/relay-hooks/ProfilerContext")}),98);
__d("HeroInteractionContextPassthrough.react",["HeroCurrentInteractionForLoggingContext","HeroInteractionContext","HeroInteractionIDContext","RelayProfilerContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react")),j=h.use,k={current:null},l={consumeBootload:function(){},retainQuery:function(){},wrapPrepareQueryResource:function(a){return a()}};function a(a){var b=a.children;a=a.clear;a=a===void 0?!0:a;return i.jsx(d("HeroInteractionContext").Context.Provider,{value:a?d("HeroInteractionContext").DEFAULT_CONTEXT_VALUE:j(d("HeroInteractionContext").Context),children:i.jsx(c("HeroCurrentInteractionForLoggingContext").Provider,{value:a?k:j(c("HeroCurrentInteractionForLoggingContext")),children:i.jsx(c("HeroInteractionIDContext").Provider,{value:a?null:j(c("HeroInteractionIDContext")),children:i.jsx(c("RelayProfilerContext").Provider,{value:a?l:j(c("RelayProfilerContext")),children:b})})})})}a.displayName=a.name+" [from "+f.id+"]";a.displayName="HeroInteractionContextPassthrough";g["default"]=a}),98);
__d("HeroPendingPlaceholderTracker",[],(function(a,b,c,d,e,f){"use strict";var g=new Map();function a(a){g.has(a)||g.set(a,new Map())}function b(a,b,c,d,e){a=g.get(a);a&&a.set(b,{description:c,startTime:d,pageletStack:e})}function c(a){a=g.get(a);return a?Array.from(a.values()):[]}function d(a){g["delete"](a)}function e(a,b){a=g.get(a);a&&a["delete"](b)}function h(a){return g.has(a)}f.addInteraction=a;f.addPlaceholder=b;f.dump=c;f.removeInteraction=d;f.removePlaceholder=e;f.isInteractionActive=h}),66);
__d("HeroFallbackTracker.react",["HeroInteractionContext","HeroInteractionIDContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useContext,j=b.useLayoutEffect;function a(a){var b=d("react-compiler-runtime").c(5),e=a.uuid,f=i(d("HeroInteractionContext").Context),g=i(c("HeroInteractionIDContext")),h;b[0]!==f||b[1]!==g||b[2]!==e?(a=function(){if(g!=null){f.registerPlaceholder(g,e,f.pageletStack);return function(){f.removePlaceholder(g,e)}}},h=[f,g,e],b[0]=f,b[1]=g,b[2]=e,b[3]=a,b[4]=h):(a=b[3],h=b[4]);j(a,h);return null}a.displayName="HeroFallbackTracker";g["default"]=a}),98);
__d("HeroPlaceholderUtils",["PromiseAnnotate"],(function(a,b,c,d,e,f,g){"use strict";var h,i=0;function a(){return String(i++)}function b(a){if(a!=null&&a.size>0)return Array.from(a).map(function(a){a=(h||(h=d("PromiseAnnotate"))).getDisplayName(a);if(a!=null)return a;else return"Promise"}).join(",");else return null}g.getSimpleUUID=a;g.createThenableDescription=b}),98);
__d("HeroPlaceholder.react",["HeroFallbackTracker.react","HeroInteractionContext","HeroInteractionIDContext","HeroPlaceholderUtils","react","react-compiler-runtime","useStable"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;b.useCallback;var j=b.useContext,k=b.useLayoutEffect,l=b.useRef;e=function(a){a=a.children;return a};function m(a){var b=d("react-compiler-runtime").c(2),c=a.cb,e=l(!1);b[0]!==c?(a=function(){e.current||(c(),e.current=!0)},b[0]=c,b[1]=a):a=b[1];k(a);return null}function a(a){var b=d("react-compiler-runtime").c(35),e=a.children,f=a.fallback,g=a.name,h=a.unstable_avoidThisFallback,n=a.unstable_onSuspense,o=j(d("HeroInteractionContext").Context),p=j(c("HeroInteractionIDContext")),q=c("useStable")(d("HeroPlaceholderUtils").getSimpleUUID),r=(a=a.placeholderUUID)!=null?a:q,s=c("useStable")(d("HeroPlaceholderUtils").getSimpleUUID),t=l(!1);a=e;b[3]!==o||b[4]!==p||b[5]!==g||b[6]!==r||b[7]!==n?(q=function(a){p!=null&&o.suspenseCallback(p,r,o.pageletStack,a,g!=null?g:"Unnamed Suspense");if(n){a=(a=d("HeroPlaceholderUtils").createThenableDescription(a))!=null?a:"";n(a)}},b[3]=o,b[4]=p,b[5]=g,b[6]=r,b[7]=n,b[8]=q):q=b[8];e=q;var u;b[9]!==o||b[10]!==p||b[11]!==g||b[12]!==s?(q=function(){if(t.current===!1&&p!=null&&p!=null){o.hold(p,o.pageletStack,"Hydration",s,g);return function(){return o.unhold(p,s)}}},u=[o,p,g,s],b[9]=o,b[10]=p,b[11]=g,b[12]=s,b[13]=q,b[14]=u):(q=b[13],u=b[14]);k(q,u);b[15]!==o||b[16]!==p||b[17]!==s?(q=function(){t.current=!0,p!=null&&o.unhold(p,s)},b[15]=o,b[16]=p,b[17]=s,b[18]=q):q=b[18];u=q;b[19]!==u?(q=i.jsx(m,{cb:u}),b[19]=u,b[20]=q):q=b[20];var v;b[21]!==r?(v=i.jsx(c("HeroFallbackTracker.react"),{uuid:r}),b[21]=r,b[22]=v):v=b[22];var w;b[23]!==f||b[24]!==q||b[25]!==v?(w=i.jsxs(i.Fragment,{children:[f,q,v]}),b[23]=f,b[24]=q,b[25]=v,b[26]=w):w=b[26];b[27]!==u?(f=i.jsx(m,{cb:u}),b[27]=u,b[28]=f):f=b[28];b[29]!==e||b[30]!==w||b[31]!==f||b[32]!==h||b[33]!==a?(q=i.jsxs(i.Suspense,{fallback:w,suspenseCallback:e,unstable_avoidThisFallback:h,children:[f,a]}),b[29]=e,b[30]=w,b[31]=f,b[32]=h,b[33]=a,b[34]=q):q=b[34];return q}a.displayName="HeroPlaceholder";g["default"]=a}),98);
__d("hero-tracing-placeholder",["HeroComponent.react","HeroCurrentInteractionForLoggingContext","HeroHoldTrigger.react","HeroInteractionContext","HeroInteractionContextPassthrough.react","HeroInteractionIDContext","HeroPendingPlaceholderTracker","HeroPlaceholder.react","HeroPlaceholderUtils"],(function(a,b,c,d,e,f,g){"use strict";g.HeroComponent=c("HeroComponent.react"),g.HeroHoldTrigger=c("HeroHoldTrigger.react"),g.HeroInteractionContext=d("HeroInteractionContext"),g.HeroInteractionContextPassthrough=c("HeroInteractionContextPassthrough.react"),g.HeroInteractionIDContext=c("HeroInteractionIDContext"),g.HeroCurrentInteractionForLoggingContext=c("HeroCurrentInteractionForLoggingContext"),g.HeroPendingPlaceholderTracker=d("HeroPendingPlaceholderTracker"),g.HeroPlaceholder=c("HeroPlaceholder.react"),g.HeroPlaceholderUtils=d("HeroPlaceholderUtils")}),98);
__d("InlineFbtResult",["cr:1183579"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:1183579")}),98);
__d("InlineFbtResultImplComet",["FbtHooks","FbtReactUtil","FbtResultBase","react","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react");function k(a){var b=a.content,d=a.hash,e=a.inlineMode;a=a.translation;d==null&&c("recoverableViolation")('Fbt string hash should not be null for translated string "'+a+'" '+("[inlineMode="+e+"]"),"internationalization");return j.jsx("span",{"data-intl-hash":d,"data-intl-translation":a,"data-intl-trid":"",children:b})}k.displayName=k.name+" [from "+f.id+"]";a=function(a){babelHelpers.inheritsLoose(b,a);function b(b,e,f,g){var i;i=a.call(this,b,(h||(h=c("FbtHooks"))).getErrorListener({hash:g,translation:f}))||this;i.$$typeof=d("FbtReactUtil").REACT_ELEMENT_TYPE;i.key=null;i.ref=null;i.type=k;i.props={content:b,hash:g,inlineMode:e,translation:f};return i}return b}(c("FbtResultBase"));g["default"]=a}),98);
__d("TransAppInlineMode",[],(function(a,b,c,d,e,f){a=Object.freeze({STRING_MANAGER:"STRING_MANAGER",TRANSLATION:"TRANSLATION",APPROVE:"APPROVE",REPORT:"REPORT",NO_INLINE:"NO_INLINE"});f["default"]=a}),66);
__d("deferredLoadComponentBase",["ExecutionEnvironment","Promise","PromiseAnnotate","react","suspendOrThrowIfUsedInSSR"],(function(a,b,c,d,e,f,g){var h,i,j,k,l,m=l||c("react"),n={},o={},p=new Map();function q(a,b){p.set(a,b)}function r(a){return p.get(a)}function a(a,e){var g=r(a);if(g)return g;var l,p=a.getModuleId();function s(){var c=o[p];c||(c=o[p]=new(i||(i=b("Promise")))(function(b){a.loadImmediately(function(a){delete o[p],l=e(a),b()})}));return c}function t(){var c=n[p];c||(c=n[p]=new(i||(i=b("Promise")))(function(b){a.onReady(function(a){l=e(a),delete n[p],b()})}));return c}function u(b){var f=b.ref;b=babelHelpers.objectWithoutPropertiesLoose(b,["ref"]);var g=b.loadImmediately;b=babelHelpers.objectWithoutPropertiesLoose(b,["loadImmediately"]);if(!l){var i=a.getModuleIfRequireable();i!=null&&(l=e(i));if(!l){!(j||(j=c("ExecutionEnvironment"))).isInBrowser&&!a.isAvailableInSSR_DO_NOT_USE()&&(k||(k=c("suspendOrThrowIfUsedInSSR")))("Loading bootloaded and T3 components are disabled during SSR");i=g===!0?s():t();(h||(h=d("PromiseAnnotate"))).setDisplayName(i,u.displayName);throw i}}return m.jsx(l,babelHelpers["extends"]({},b,{ref:f}))}u.displayName=u.name+" [from "+f.id+"]";g=a.getModuleId();a.isRequireDeferredForDisplay()===!0?g="requireDeferredForDisplay"+("("+a.getModuleId()+")"):a.isRequireDeferredForDisplay()===!1&&(g="requireDeferred"+("("+a.getModuleId()+")"));u.displayName="deferredLoadComponent("+g+")";g=u;q(a,g);return g}g["default"]=a}),98);
__d("deferredLoadComponent",["deferredLoadComponentBase"],(function(a,b,c,d,e,f,g){var h=function(a){return a};function a(a){return c("deferredLoadComponentBase")(a,h)}g["default"]=a}),98);
__d("WAWebKeyboardRotateFocusModal.react",["WAWebKeyboardConstants","WAWebKeyboardTabUtils","react","stylex","useMergeRefs"],(function(a,b,c,d,e,f,g){var h,i,j,k=j||c("react"),l=(h||(h=d("react"))).useRef,m={container:{position:"x10l6tqk",top:"x13vifvy",insetInlineEnd:"xtijo5x",bottom:"x1ey2m1c",insetInlineStart:"x1o0tod",$$css:!0}};function a(a){var b=a.children,e=a.focusType,f=a.onBlur,g=a.ref;a=a.xstyle;var h=l(null);g=c("useMergeRefs")(g,h);var j=function(a){var b=h.current;if(!b)return;var c=a.shiftKey?d("WAWebKeyboardTabUtils").TabDirection.BACKWARD:d("WAWebKeyboardTabUtils").TabDirection.FORWARD,f=e!=null?e:{type:d("WAWebKeyboardTabUtils").FocusType.TABBABLE},g=f.type;f=f.customSelector;b=d("WAWebKeyboardTabUtils").getNextTabbableElement(b,c,g,void 0,f);if(b==null)return;a.preventDefault();b.focus()},n=function(a){if(a.metaKey||a.ctrlKey)return;if(a.key===d("WAWebKeyboardConstants").KEYBOARD_EVENT_KEY_VALUE.TAB)return j(a)};return k.jsx("div",babelHelpers["extends"]({ref:g},(i||(i=c("stylex"))).props(m.container,a),{onKeyDown:n,tabIndex:-1,onBlur:f,children:b}))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("getUnwrappedFbt",["FbtResultGK"],(function(a,b,c,d,e,f){function a(a){a=a.contents;var c=b("FbtResultGK").inlineMode,d=b("FbtResultGK").shouldReturnFbtResult;if(!d&&c!=="REPORT")return(a==null?void 0:a.length)===1&&typeof a[0]==="string"?a[0]:a}e.exports=a}),null);
__d("getFbtResult",["FbtResult","FbtResultGK","InlineFbtResult","getUnwrappedFbt","gkx","recoverableViolation"],(function(a,b,c,d,e,f,g){c("gkx")("20935")&&c("FbtResultGK").inlineMode==="TRANSLATION"&&c("recoverableViolation")("TransAppInlineMode=TRANSLATION should not happen on Comet yet. "+("[inlineMode="+(c("FbtResultGK").inlineMode!=null?c("FbtResultGK").inlineMode:"")+"]")+("[runtime_site_is_comet="+String(c("gkx")("20935"))+"]"),"internationalization");function a(a){var b=c("getUnwrappedFbt")(a);if(b!=null)return b;b=a.contents;var d=a.patternString,e=a.patternHash;return c("FbtResultGK").inlineMode!=null&&c("FbtResultGK").inlineMode!=="NO_INLINE"?new(c("InlineFbtResult"))(b,c("FbtResultGK").inlineMode,d,e):c("FbtResult").get(a)}g["default"]=a}),98);/*FB_PKG_DELIM*/
/**
 * License: https://www.facebook.com/legal/license/V9vdYColc4k/
 */
__d("react-0.0.0",["React"],(function(a,b,c,d,e,f){"use strict";function a(a){return a&&typeof a==="object"&&"default"in a?a["default"]:a}var g=a(b("React"));d={};var h={exports:d};function i(){h.exports=g}var j=!1;function k(){j||(j=!0,i());return h.exports}function c(a){switch(a){case void 0:return k()}}e.exports=c}),null);
__d("react",["react-0.0.0"],(function(a,b,c,d,e,f){e.exports=b("react-0.0.0")()}),null);/*FB_PKG_DELIM*/
__d("CometRouterDispatcherContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext();g["default"]=b}),98);
__d("CometSSRClientRender",[],(function(a,b,c,d,e,f){"use strict";var g="CometSSRClientRenderError";function a(a){throw g+": "+a}f.CometSSRClientRenderErrorSentinel=g;f.CometSSRClientRender=a}),66);
__d("suspendOrThrowIfUsedInSSR",["CometSSRClientRender","ExecutionEnvironment"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){if(!(h||(h=c("ExecutionEnvironment"))).isInBrowser)throw d("CometSSRClientRender").CometSSRClientRender(a)}g["default"]=a}),98);